apiVersion: apps/v1
kind: Deployment
metadata:
  name: central-rakuten-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: central-rakuten-backend
  template:
    metadata:
      labels:
        app: central-rakuten-backend
    spec:
      containers:
        - name: central-rakuten-backend-container
          image: registry.digitalocean.com/oondemand/central-rakuten-backend:0.0.4
          ports:
            - containerPort: 4000
          resources:
            requests:
              memory: "256Mi"
              cpu: "0.1"
            limits:
              memory: "2048Mi"
              cpu: "2"

---
apiVersion: v1
kind: Service
metadata:
  name: central-rakuten-backend-service
spec:
  type: LoadBalancer
  selector:
    app: central-rakuten-backend
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 4000
